# Generated by Django 5.0 on 2023-12-31 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='created',
            field=models.TimeField(default='19:10:26'),
        ),
    ]
